# infrastructure/nginx-ingress/argocd-nginx-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: argocd 
spec:
  project: dolibarr 

  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.0 
    
    chart: ingress-nginx
    
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/Vitadek/dolibarr-argo/refs/heads/main/infrastructure/nginx-ingress-controller/values.yaml 

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
