
replicaCount: 1

keepAlive: false #pod will stay alive even after dolibarr crashes

initContainers:
  enabled: false # the initcontainer will run before the pod fully deploys. Can be turned off/on by setting false/false. Modify deployment.yaml for more granularity.
  command: |
    set -e 
    
    echo "initContainers is enabled. Starting file setup..."
    echo "Downloading file to /data/dolibarr-html.tar.gz..."
    wget -O /data/dolibarr-html.tar.gz https://github.com/Vitadek/dolibarr-argo/raw/refs/heads/main/data/var-www-html/dolibarr-html.tar.gz
    
    echo "Download successful. Extracting file into the shared /data volume..."
    # Corrected the filename and the extraction path (-C /data)
    tar -xvf /data/dolibarr-html.tar.gz -C /var/www/

    echo "Extraction successful. Cleaning up archive..."
    rm -f /data/dolibarr-html.tar.gz

    echo "File setup complete. Exiting initContainer."

image:
  repository: dolibarr/dolibarr
  pullPolicy: IfNotPresent
  tag: "19"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  #fsGroup: 33

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  certManagerClusterIssuer: "letsencrypt-prod"
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: dolibarr-hidoe.powerstech.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - dolibarr.yourdomain.com
      secretName: dolibarr-hidoe-tls

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 15
  preiodSeconds: 10
  timeoutSeconds: 5
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  preiodSeconds: 10
  timeoutSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

database:
  type: mysqli
  port: 42069
  name: dolibarr_db
  user: dolibarr_user
  existingSecret: dolibarr-db-secret
  secretKey: db-password
  hostSecretKey: db-host
  ssl:
    enabled: true
    caSecretName: mariadb-ca-cert
    caSecretKey: ca.pem

persistence:
  enabled: true
  size: 5Gi
  StorageClassName: linode-block-storage-retain

appConfig:
  configMapName: dolibarr-app-config
  ingressHostKey: ingress-host
  urlRootKey: dolibarr-url-root

phpIni:
  dateTimezone: "HST"
  memoryLimit: "256M"
  uploadMaxFilesize: "2M"
  postMaxSize: "8M"
  allowUrlFopen: "0"

ldap:
  auth: "dolibarr"
  host: "127.0.0.1"
  port: 389
  version: "3"
  serverType: "openldap"
  loginAttribute: "uid"
  dn: "ou=users,dc=my-domain,dc=com"
  filter: ""
  bindDn: ""
  bindPass: ""
  debug: "false"

dolibarrConfig:
  installAuto: "1"
  initDemo: "0"
  prod: "0"
  companyName: ""
  companyCountryCode: ""
  instanceUniqueId: ""
  adminLogin: "admin"
  enableModules: "Societe,Facture,Stock"
  cron: "0"
  cronKey: "mycronsecurekey"
  cronUser: ""
  wwwUserId: ""

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
