apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # The name of the application in ArgoCD
  name: longhorn
  # It's best practice to deploy applications into the argocd namespace
  namespace: argocd
spec:
  # The ArgoCD project this application belongs to
  project: default

  # Source of the application definition
  source:
    # The official Longhorn Helm chart repository
    repoURL: https://charts.longhorn.io
    # The name of the chart to deploy
    chart: longhorn
    # Pinning to a specific version for stability
    targetRevision: 1.6.2
    helm:
      # The release name for the Helm deployment
      releaseName: longhorn

  # Destination where the application will be deployed
  destination:
    # The target Kubernetes cluster URL
    server: https://kubernetes.default.svc
    # The namespace to install Longhorn into
    namespace: longhorn-system

  # Sync policy
  syncPolicy:
    # Enable automated synchronization
    automated:
      # Allows ArgoCD to delete resources that are no longer in the Helm chart
      prune: true
      # Allows ArgoCD to automatically sync when it detects a difference
      selfHeal: true
    # Additional sync options
    syncOptions:
      # This will create the 'longhorn-system' namespace if it doesn't exist
      - CreateNamespace=true

