apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dolibarr-chart.fullname" . }}-pvc
  labels:
    {{- include "dolibarr-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
